name: .NET CI

on:
  push:
    branches: [ main, develop, release/*, hotfix/*, feature/* ]
    paths:
      - 'afi_loadboad_api/Services/Auth.API/**'

  pull_request:
    branches: [ main, develop, feature/*, release/*, hotfix/*]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: Services/Auth.API

    - name: Build
      run: dotnet build --no-restore
      working-directory: Services/Auth.API

    - name: Test
      run: dotnet test --no-build

    - name: Install dotnet-format (Linter)
      run: dotnet tool install -g dotnet-format

    - name: Run dotnet-format (Linter)
      run: dotnet format --check
      working-directory: Services/Auth.API
